<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QPLUSL4" failures="1" tests="3" name="FirefoxTest" time="27.292" errors="0" timestamp="2022-03-27T21:09:38 IST">
  <testcase classname="testPack.VerifyUserCreated" name="custemerName" time="0.311"/>
  <testcase classname="testPack.VerifyHeaderTabs" name="verifyTaskTab" time="4.037"/>
  <testcase classname="testPack.VerifyHeaderTabs" name="verifyTimeTrackTab" time="2.503">
    <failure type="java.lang.AssertionError" message="expected [http://localhost/user/submit_tt.] but found [http://localhost/user/submit_tt.do]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost/user/submit_tt.] but found [http://localhost/user/submit_tt.do]
at testPack.VerifyHeaderTabs.verifyTimeTrackTab(VerifyHeaderTabs.java:96)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyTimeTrackTab -->
</testsuite> <!-- FirefoxTest -->
